export const JOB_CATEGORIES = [
  '3Ds Max Designer',
  'Accountant',
  'Administration',
  'Architect',
  'Architectural / Model Designer',
  'Assistant',
  'Autocad Expert / Trainee',
  'Ayurveda Therapist',
  'Banking jobs',
  'Beautician',
  'Billing Staff',
  'BPO jobs',
  'Branch Manager',
  'Business Development',
  'Cashier',
  'Cleaning / Other jobs',
  'Co-ordinator',
  'Computer Operator',
  'Construction / Supervising',
  'Content / Copy Writer',
  'Cook / Chef',
  'Counsellor',
  'CRM',
  'Customer Relation Officer',
  'Data Analyst',
  'Data Entry',
  'Delivery Boy',
  'Digital Marketing',
  'Driver',
  'DTP Operator',
  'Electrician',
  'Engineer - Civil',
  'Engineer - Mechanical',
  'Executive',
  'Executive Asst., Front Office',
  'Faculty',
  'Fashion Design',
  'Finance',
  'Graphic Design',
  'Helper',
  'Holiday Consultant',
  'House Keeping',
  'HR Consultant',
  'HR/Admin',
  'Interior Designer',
  'IT jobs',
  'Java Developer',
  'Lab Technician',
  'Manager',
  'Mechanic',
  'Medical/Health care',
  'Mobile App Developer',
  'Mobile Technician',
  'Network Administration',
  'Nurse',
  'Office Co-Ordinator',
] as const;

export const COMPANY = {
  name: 'IBees Jobs',
  tagline: 'Connecting Talent with Opportunities',
  email: 'balasankar8943@gmail.com',
  phones: ['+91 8075946173'],
  whatsapp: '918075946173',
  address: 'TC. 97/2440, Near Infosys, Thampuranmukku, Kazhakootom, Thiruvananthapuram, Kerala 695583',
} as const;

export const APPLICATION_STATUSES = ['pending', 'shortlisted', 'rejected'] as const;
