import { Job } from './types';

export const JOB_CATEGORIES = [
  '3Ds Max Designer', 'Accountant', 'Administration', 'Architect',
  'Architectural / Model Designer', 'Assistant', 'Autocad Expert / Trainee', 'Ayurveda Therapist',
  'Banking jobs', 'Beautician', 'Billing Staff', 'BPO jobs',
  'Branch Manager', 'Business Development', 'Cashier', 'Cleaning / Other jobs',
  'Co-ordinator', 'Computer Operator', 'Construction / Supervising', 'Content / Copy Writer',
  'Cook / Chef', 'Counsellor', 'CRM', 'Customer Relation Officer',
  'Data Analyst', 'Data Entry', 'Delivery Boy', 'Digital Marketing',
  'Driver', 'DTP Operator', 'Electrician', 'Engineer - Civil',
  'Engineer - Mechanical', 'Executive', 'Executive Asst., Front Office', 'Faculty',
  'Fashion Design', 'Finance', 'Graphic Design', 'Helper',
  'Holiday Consultant', 'House Keeping', 'HR Consultant', 'HR/Admin',
  'Interior Designer', 'IT jobs', 'Java Developer', 'Lab Technician',
  'Manager', 'Mechanic', 'Medical/Health care', 'Mobile App Developer',
  'Mobile Technician', 'Network Administration', 'Nurse', 'Office Co-Ordinator'
] as const;

export const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || '';

export const COMPANY = {
  name: 'IBees Jobs',
  tagline: 'Connecting Talent with Opportunities',
  email: 'ibeesjobs@gmail.com',
  phones: ['+91 62380 78365', '+91 95444 29313', '+91 70126 32399'],
  whatsapp: '919544429313',
  address: 'TC. 97/2440, Near Infosys, Thampuranmukku, Kazhakootom, Thiruvananthapuram, Kerala, India, 695583',
} as const;

// Utility helper to group 56 categories into 3 main sectors
export function getSectorForCategory(category: string): 'IT' | 'Non-IT' | 'Abroad' {
  const IT_CATEGORIES = [
    '3Ds Max Designer', 'Autocad Expert / Trainee', 'Computer Operator',
    'Data Analyst', 'Digital Marketing', 'DTP Operator', 'Graphic Design',
    'IT jobs', 'Java Developer', 'Mobile App Developer', 'Mobile Technician',
    'Network Administration'
  ];

  const ABROAD_CATEGORIES = [
    'Ayurveda Therapist', 'Cook / Chef', 'Engineer - Civil',
    'Engineer - Mechanical', 'Nurse'
  ];

  if (IT_CATEGORIES.includes(category)) return 'IT';
  if (ABROAD_CATEGORIES.includes(category)) return 'Abroad';
  return 'Non-IT';
}

export const STATIC_JOBS: Job[] = [
  {
    id: '1',
    title: '3Ds Max Designer',
    category: '3Ds Max Designer',
    description: 'We are seeking an experienced 3Ds Max Designer for architectural visualization and product rendering. Must be proficient in V-Ray rendering, polygon modeling, and camera setups.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹30,000 - ₹45,000/month',
    qualification: 'Degree/Diploma in Design/Animation',
    experience: '3+ years',
    is_active: true,
    created_at: '2026-06-25T10:00:00Z'
  },
  {
    id: '2',
    title: 'Accountant',
    category: 'Accountant',
    description: 'Required Accountant to manage commercial tax files, balance sheets, and audit preparations. Knowledge of Tally ERP9 and GST filing is mandatory.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹22,000 - ₹32,000/month',
    qualification: 'B.Com / M.Com',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T10:15:00Z'
  },
  {
    id: '3',
    title: 'Administration',
    category: 'Administration',
    description: 'Looking for a dedicated administrator to coordinate company schedules, handle client communications, and maintain office records. Strong office management and MS Office skills required.',
    location: 'Kochi, Kerala',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹28,000/month',
    qualification: 'Any Graduate',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T10:30:00Z'
  },
  {
    id: '4',
    title: 'Architect',
    category: 'Architect',
    description: 'Architect needed to design premium residential layouts. Must be expert in SketchUp, Revit, and space planning structures.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹35,000 - ₹55,000/month',
    qualification: 'B.Arch',
    experience: '3+ years',
    is_active: true,
    created_at: '2026-06-25T10:45:00Z'
  },
  {
    id: '5',
    title: 'Architectural / Model Designer',
    category: 'Architectural / Model Designer',
    description: 'Create detailed physical scale models and digital prototypes for major commercial projects. Creative design thinking and structural detailing are essential.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹25,000 - ₹38,000/month',
    qualification: 'Diploma in Architecture/Interior Design',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T11:00:00Z'
  },
  {
    id: '6',
    title: 'Assistant',
    category: 'Assistant',
    description: 'Provide general office assistance including file management, data entry, and guest welcoming. Freshers with good behavior and office etiquette are welcome.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹12,000 - ₹18,000/month',
    qualification: '+2 / Any Degree',
    experience: 'Freshers preferred',
    is_active: true,
    created_at: '2026-06-25T11:15:00Z'
  },
  {
    id: '7',
    title: 'Autocad Expert / Trainee',
    category: 'Autocad Expert / Trainee',
    description: 'AutoCAD draftsmen needed for creating civil structural drawings. Trainee positions are open for fresh technical school graduates.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹28,000/month',
    qualification: 'ITC / Diploma in Civil Draftsman',
    experience: '0 - 2 years',
    is_active: true,
    created_at: '2026-06-25T11:30:00Z'
  },
  {
    id: '8',
    title: 'Ayurveda Therapist',
    category: 'Ayurveda Therapist',
    description: 'Certified Ayurveda Therapist required for wellness resort. Deep knowledge of Panchakarma and traditional massage procedures is necessary.',
    location: 'Germany Deployment',
    type: 'Full-time',
    salary_range: '₹1,60,000 - ₹2,40,000/month',
    qualification: 'Diploma in Ayurveda Therapy / BAMS',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T11:45:00Z'
  },
  {
    id: '9',
    title: 'Banking jobs',
    category: 'Banking jobs',
    description: 'Handle customer relationship desks, retail credit processing, and KYC audit management for private banking and financial institutions.',
    location: 'Kollam, Kerala',
    type: 'Full-time',
    salary_range: '₹22,000 - ₹34,000/month',
    qualification: 'Any Degree / MBA Finance',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T12:00:00Z'
  },
  {
    id: '10',
    title: 'Beautician',
    category: 'Beautician',
    description: 'Leading beauty salon is hiring an expert beautician proficient in hair treatment, skin care, styling, and bridal makeup.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹25,000/month',
    qualification: 'Certificate in Cosmetology/Beauty Therapy',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T12:15:00Z'
  },
  {
    id: '11',
    title: 'Billing Staff',
    category: 'Billing Staff',
    description: 'Required billing clerks for supermarket checkout desks. Must have familiarity with barcode systems, POS machines, and cash counting.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹13,000 - ₹18,000/month',
    qualification: '10th / +2 passed',
    experience: 'Freshers welcome',
    is_active: true,
    created_at: '2026-06-25T12:30:00Z'
  },
  {
    id: '12',
    title: 'BPO jobs',
    category: 'BPO jobs',
    description: 'Resolve client complaints and represent global brands for international call centers. Excellent English verbal fluency and listening skills required.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹28,000/month',
    qualification: 'Higher Secondary / Any Degree',
    experience: 'Freshers & Experienced',
    is_active: true,
    created_at: '2026-06-25T12:45:00Z'
  },
  {
    id: '13',
    title: 'Branch Manager',
    category: 'Branch Manager',
    description: 'Oversee daily sales targets, manage local branch employees, and optimize operational profit margins for the center.',
    location: 'Kochi, Kerala',
    type: 'Full-time',
    salary_range: '₹35,000 - ₹50,000/month',
    qualification: 'MBA Operations / Management Graduate',
    experience: '4+ years',
    is_active: true,
    created_at: '2026-06-25T13:00:00Z'
  },
  {
    id: '14',
    title: 'Business Development',
    category: 'Business Development',
    description: 'Responsible for growing business partnerships, identifying sales leads, pitching services, and maintaining customer relations.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹22,000 - ₹35,000/month + incentives',
    qualification: 'MBA Marketing / BBA',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T13:15:00Z'
  },
  {
    id: '15',
    title: 'Cashier',
    category: 'Cashier',
    description: 'Accurate transaction processing, invoice generation, and bank deposits clearance. Basic accounting math proficiency required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹14,000 - ₹20,000/month',
    qualification: '+2 / B.Com',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T13:30:00Z'
  },
  {
    id: '16',
    title: 'Cleaning / Other jobs',
    category: 'Cleaning / Other jobs',
    description: 'Clean facility floors, manage office dust bins, and help arrange warehouse inventories. Good physical health and discipline required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹10,000 - ₹14,000/month',
    qualification: 'SSLC / School dropouts welcome',
    experience: 'No experience needed',
    is_active: true,
    created_at: '2026-06-25T13:45:00Z'
  },
  {
    id: '17',
    title: 'Co-ordinator',
    category: 'Co-ordinator',
    description: 'Coordinate operations between the sales divisions and shipping departments. Strong email drafting and communication skills needed.',
    location: 'Kochi, Kerala',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹25,000/month',
    qualification: 'Any Degree',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T14:00:00Z'
  },
  {
    id: '18',
    title: 'Computer Operator',
    category: 'Computer Operator',
    description: 'Type customer profiles, upload logistics schedules, and manage spreadsheet archives. Good typing speed and basic computer troubleshooting required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹12,000 - ₹18,000/month',
    qualification: 'DCA / Microsoft Office Suite certificate',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T14:15:00Z'
  },
  {
    id: '19',
    title: 'Construction / Supervising',
    category: 'Construction / Supervising',
    description: 'Supervise site construction processes, check material logs, and report building progress to project managers.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹30,000/month',
    qualification: 'Diploma in Civil Engineering / ITI',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T14:30:00Z'
  },
  {
    id: '20',
    title: 'Content / Copy Writer',
    category: 'Content / Copy Writer',
    description: 'Write engaging blog posts, social media promotions, and advertising brochures. Excellent English grammar and SEO writing skills needed.',
    location: 'Remote / Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹28,000/month',
    qualification: 'Degree in English Literature / Journalism',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T14:45:00Z'
  },
  {
    id: '21',
    title: 'Cook / Chef',
    category: 'Cook / Chef',
    description: 'Experienced multi-cuisine cook required. Expertise in preparation of traditional Indian, Arabic, and continental culinary dishes preferred.',
    location: 'Saudi Arabia Deployment',
    type: 'Full-time',
    salary_range: '₹80,000 - ₹1,20,000/month',
    qualification: 'Diploma in Food Production / Experience certificate',
    experience: '3+ years',
    is_active: true,
    created_at: '2026-06-25T15:00:00Z'
  },
  {
    id: '22',
    title: 'Counsellor',
    category: 'Counsellor',
    description: 'Advise students on academic higher education routes, manage admission applications, and guide profile credentials checks.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹26,000/month',
    qualification: 'Any Degree',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T15:15:00Z'
  },
  {
    id: '23',
    title: 'CRM',
    category: 'CRM',
    description: 'Manage sales databases using standard CRM platforms. Analyze data trends and coordinate customer engagement campaigns.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹22,000 - ₹30,000/month',
    qualification: 'Graduation',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T15:30:00Z'
  },
  {
    id: '24',
    title: 'Customer Relation Officer',
    category: 'Customer Relation Officer',
    description: 'Represent the brand at front office receptions. Excellent communication, welcoming posture, and customer issue resolution skills needed.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹22,000/month',
    qualification: 'Degree in Hospitality / Any Graduate',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T15:45:00Z'
  },
  {
    id: '25',
    title: 'Data Analyst',
    category: 'Data Analyst',
    description: 'Clean raw marketing databases, query logistics trends via SQL, and present visualization dashboards using PowerBI or Tableau.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹28,000 - ₹45,000/month',
    qualification: 'B.Tech / BCA / MCA / Mathematics Degree',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T16:00:00Z'
  },
  {
    id: '26',
    title: 'Data Entry',
    category: 'Data Entry',
    description: 'Input shipment details and product catalog updates. Minimum typing speed of 40 WPM with high accuracy and attention to detail required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹12,000 - ₹16,000/month',
    qualification: '+2 passed / DCA',
    experience: 'Freshers welcome',
    is_active: true,
    created_at: '2026-06-25T16:15:00Z'
  },
  {
    id: '27',
    title: 'Delivery Boy',
    category: 'Delivery Boy',
    description: 'Deliver packages safely to local customer locations. Must own a smartphone, two-wheeler, and have a valid driving license.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹14,000 - ₹20,000/month + fuel allowances',
    qualification: '10th / SSLC / Driving License',
    experience: 'Familiarity with local routes',
    is_active: true,
    created_at: '2026-06-25T16:30:00Z'
  },
  {
    id: '28',
    title: 'Digital Marketing',
    category: 'Digital Marketing',
    description: 'Create Google Ad campaigns, manage social media branding, and track search engine keyword index optimizations.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹32,000/month',
    qualification: 'Certification in Digital Marketing',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T16:45:00Z'
  },
  {
    id: '29',
    title: 'Driver',
    category: 'Driver',
    description: 'Drive corporate directors and business clients. Must have excellent driving ethics and valid commercial driving license with clean records.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹16,000 - ₹22,000/month',
    qualification: 'LMV License / Clean background check',
    experience: '3+ years',
    is_active: true,
    created_at: '2026-06-25T17:00:00Z'
  },
  {
    id: '30',
    title: 'DTP Operator',
    category: 'DTP Operator',
    description: 'Layout Malayalam and English textbooks, prepare printing plates, and coordinate publishing design layouts.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹14,000 - ₹20,000/month',
    qualification: 'Certificate in Desktop Publishing / PageMaker / InDesign',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T17:15:00Z'
  },
  {
    id: '31',
    title: 'Electrician',
    category: 'Electrician',
    description: 'Install building wiring, repair switchboards, and manage commercial power panels. Valid wireman license required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹26,000/month',
    qualification: 'ITI Electrical / Wireman License',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T17:30:00Z'
  },
  {
    id: '32',
    title: 'Engineer - Civil',
    category: 'Engineer - Civil',
    description: 'Coordinate structure construction at major sites. Prepare engineering cost estimates, check concrete quality, and manage safety checklists.',
    location: 'GCC / Europe Deployment',
    type: 'Full-time',
    salary_range: '₹1,30,000 - ₹2,00,000/month',
    qualification: 'B.Tech in Civil Engineering',
    experience: '3+ years',
    is_active: true,
    created_at: '2026-06-25T17:45:00Z'
  },
  {
    id: '33',
    title: 'Engineer - Mechanical',
    category: 'Engineer - Mechanical',
    description: 'Manage factory machinery maintenance, pipeline checks, and coordinate equipment preventative shutdowns and safety standards.',
    location: 'GCC Deployment',
    type: 'Full-time',
    salary_range: '₹1,50,000 - ₹2,20,000/month',
    qualification: 'B.Tech in Mechanical Engineering',
    experience: '4+ years',
    is_active: true,
    created_at: '2026-06-25T18:00:00Z'
  },
  {
    id: '34',
    title: 'Executive',
    category: 'Executive',
    description: 'Present business products to retail buyers, manage client accounts, coordinate logistics, and clear monthly sales targets.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹25,000/month',
    qualification: 'Graduate / BBA',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T18:15:00Z'
  },
  {
    id: '35',
    title: 'Executive Asst., Front Office',
    category: 'Executive Asst., Front Office',
    description: 'Manage executive schedules, prepare business letters, coordinate email inboxes, and receive corporate visitors.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹16,000 - ₹24,000/month',
    qualification: 'Any Degree / Secretarial Diploma',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T18:30:00Z'
  },
  {
    id: '36',
    title: 'Faculty',
    category: 'Faculty',
    description: 'Instruct classes, prepare curriculum, structure tests, and coordinate academic sessions across various educational domains.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹25,000 - ₹38,000/month',
    qualification: 'Post Graduate / NET / Teaching certification',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T18:45:00Z'
  },
  {
    id: '37',
    title: 'Fashion Design',
    category: 'Fashion Design',
    description: 'Create original fabric design concepts, manage tailor workshops, and consult boutique buyers on current fashion trends.',
    location: 'Kochi, Kerala',
    type: 'Full-time',
    salary_range: '₹22,000 - ₹34,000/month',
    qualification: 'B.Des in Fashion Design',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T19:00:00Z'
  },
  {
    id: '38',
    title: 'Finance',
    category: 'Finance',
    description: 'Prepare company investment profiles, clear accounts audit balances, track expenditures, and audit budget allocations.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹25,000 - ₹40,000/month',
    qualification: 'MBA Finance / CA Inter',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T19:15:00Z'
  },
  {
    id: '39',
    title: 'Graphic Design',
    category: 'Graphic Design',
    description: 'Design brochures, product mockups, and digital media promotions. Proficient in Photoshop, Illustrator, and other design tools.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹28,000/month',
    qualification: 'Diploma in Graphic Designing',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T19:30:00Z'
  },
  {
    id: '40',
    title: 'Helper',
    category: 'Helper',
    description: 'Help load/unload inventory boxes, clean facility racks, and prepare dispatch packaging tags. Good physical health required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹11,000 - ₹15,000/month',
    qualification: '10th standard',
    experience: 'Freshers',
    is_active: true,
    created_at: '2026-06-25T19:45:00Z'
  },
  {
    id: '41',
    title: 'Holiday Consultant',
    category: 'Holiday Consultant',
    description: 'Promote travel packages to client buyers, manage visa checks, coordinate hotel reservations, and design customized itineraries.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹28,000/month',
    qualification: 'Degree in Tourism / Hospitality',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T20:00:00Z'
  },
  {
    id: '42',
    title: 'House Keeping',
    category: 'House Keeping',
    description: 'Clean hotel guest rooms, replenish toilet items, and maintain floor hygiene rules. Hospital or hotel cleaning background preferred.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹12,000 - ₹16,000/month',
    qualification: 'SSLC passed',
    experience: 'Experience in hotels preferred',
    is_active: true,
    created_at: '2026-06-25T20:15:00Z'
  },
  {
    id: '43',
    title: 'HR Consultant',
    category: 'HR Consultant',
    description: 'Source candidate applications, screen resumes, schedule interviewer calendars, and prepare onboarding documents.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹30,000/month',
    qualification: 'MBA HR / Any Graduate',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T20:30:00Z'
  },
  {
    id: '44',
    title: 'HR/Admin',
    category: 'HR/Admin',
    description: 'Coordinate employee monthly attendance registers, check salary calculations, and handle office payroll updates.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹22,000 - ₹34,000/month',
    qualification: 'MBA HR / M.Com',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T20:45:00Z'
  },
  {
    id: '45',
    title: 'Interior Designer',
    category: 'Interior Designer',
    description: 'Create commercial interior floor planning designs. Expert in SketchUp, AutoCAD, and materials sourcing for residential or corporate structures.',
    location: 'Kochi, Kerala',
    type: 'Full-time',
    salary_range: '₹28,000 - ₹42,000/month',
    qualification: 'B.Des / Diploma in Interior Design',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T21:00:00Z'
  },
  {
    id: '46',
    title: 'IT jobs',
    category: 'IT jobs',
    description: 'Resolve local computer problems, coordinate office printer networking issues, and install/configure software packages.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹28,000/month',
    qualification: 'B.Sc Computer Science / IT / CCNA',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T21:15:00Z'
  },
  {
    id: '47',
    title: 'Java Developer',
    category: 'Java Developer',
    description: 'Build backend microservices using Java and Spring Boot. Optimize MySQL database queries and develop secure APIs.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹35,000 - ₹60,000/month',
    qualification: 'B.Tech / MCA / BCA',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T21:30:00Z'
  },
  {
    id: '48',
    title: 'Lab Technician',
    category: 'Lab Technician',
    description: 'Collect blood samples, verify pathology tests, and calibrate laboratory diagnostic instruments. DMLT/BMLT required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹22,000/month',
    qualification: 'Diploma in Medical Laboratory Technology (DMLT)',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T21:45:00Z'
  },
  {
    id: '49',
    title: 'Manager',
    category: 'Manager',
    description: 'Review project operational reports, manage project budgets, and organize multi-discipline team tasks to ensure prompt deliveries.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹40,000 - ₹60,000/month',
    qualification: 'MBA Operations / Post Graduate',
    experience: '5+ years',
    is_active: true,
    created_at: '2026-06-25T22:00:00Z'
  },
  {
    id: '50',
    title: 'Mechanic',
    category: 'Mechanic',
    description: 'Diagnose vehicle engine failures, perform diesel system changes, and coordinate automotive mechanical repairs.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹16,000 - ₹26,000/month',
    qualification: 'ITI Motor Mechanic / Automobile Diploma',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T22:15:00Z'
  },
  {
    id: '51',
    title: 'Medical/Health care',
    category: 'Medical/Health care',
    description: 'Promote healthcare products to doctors and clinics, secure wholesale contracts, and report quarterly clinic distributions.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹30,000/month',
    qualification: 'B.Pharm / B.Sc Sciences',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T22:30:00Z'
  },
  {
    id: '52',
    title: 'Mobile App Developer',
    category: 'Mobile App Developer',
    description: 'Create multi-platform mobile apps for Android and iOS using Dart and Flutter. Integrate REST APIs and state management structures.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹30,000 - ₹55,000/month',
    qualification: 'B.Tech / BCA / MCA',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T22:45:00Z'
  },
  {
    id: '53',
    title: 'Mobile Technician',
    category: 'Mobile Technician',
    description: 'Repair mobile screens, diagnose motherboard short-circuits, and swap damaged chip hardware controllers.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹25,000/month',
    qualification: 'Certificate in Mobile Phone Repairing / ITI',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T23:00:00Z'
  },
  {
    id: '54',
    title: 'Network Administration',
    category: 'Network Administration',
    description: 'Configure router firewall rules, maintain network switches, and optimize ethernet lines bandwidth.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹28,000 - ₹42,000/month',
    qualification: 'B.Tech / CCNA / CCNP certified',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T23:15:00Z'
  },
  {
    id: '55',
    title: 'Nurse',
    category: 'Nurse',
    description: 'Registered Staff Nurses required for critical care units. Sponsorship packages and visa services provided.',
    location: 'United Kingdom Deployment',
    type: 'Full-time',
    salary_range: '₹2,60,000 - ₹3,50,000/month',
    qualification: 'B.Sc Nursing / GNM + KNMC Registration + IELTS/OET',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T23:30:00Z'
  },
  {
    id: '56',
    title: 'Office Co-Ordinator',
    category: 'Office Co-Ordinator',
    description: 'Provide general administration and client operations coordination. Organize executive directories and draft business emails.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹22,000/month',
    qualification: 'Any Graduation',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-25T23:45:00Z'
  }
];
