import { Job } from './types';

export const JOB_CATEGORIES = ['IT', 'Non-IT', 'Abroad'] as const;

export const COMPANY = {
  name: 'IBees Jobs',
  tagline: 'Connecting Talent with Opportunities',
  email: 'ibeesjobs@gmail.com',
  phones: ['+91 62380 78365', '+91 95444 29313'],
  whatsapp: '919544429313', // Target number for redirects
  address: 'TC. 97/2440, Near Infosys, Thampuranmukku, Kazhakootom, Thiruvananthapuram, Kerala 695583',
} as const;

export const APPLICATION_STATUSES = ['pending', 'shortlisted', 'rejected'] as const;

export const STATIC_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior 3Ds Max Designer',
    category: 'IT',
    description: 'We are looking for a skilled 3Ds Max Designer with 3+ years of experience in architectural visualization and product rendering. Must be proficient in V-Ray rendering, modeling, and animation. Portfolio required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹25,000 - ₹40,000/month',
    qualification: 'Degree/Diploma in Animation/Design',
    experience: '3+ years',
    is_active: true,
    created_at: '2026-06-20T10:00:00Z'
  },
  {
    id: '2',
    title: 'Junior Accountant',
    category: 'Non-IT',
    description: 'Seeking a detail-oriented Junior Accountant to manage financial records, prepare reports, and assist with audits. Knowledge of Tally ERP9 and GST filing required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹25,000/month',
    qualification: 'B.Com / M.Com',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-21T10:00:00Z'
  },
  {
    id: '3',
    title: 'Office Administrator',
    category: 'Non-IT',
    description: 'Looking for an experienced Office Administrator to manage day-to-day office operations, coordinate schedules, and maintain records. Strong communication and organizational skills required.',
    location: 'Kochi, Kerala',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹30,000/month',
    qualification: 'Any Graduation',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-22T10:00:00Z'
  },
  {
    id: '4',
    title: 'Architect - Residential Projects',
    category: 'Non-IT',
    description: 'Experienced Architect needed for residential architectural planning. Must have proficiency in AutoCAD, SketchUp, and Revit. Minimum 2 years experience required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹30,000 - ₹50,000/month',
    qualification: 'B.Arch',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-23T10:00:00Z'
  },
  {
    id: '5',
    title: 'AutoCAD Draftsman',
    category: 'IT',
    description: 'AutoCAD expert needed for creating detailed technical drawings and blueprints. Experience in civil/structural drafting preferred.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹35,000/month',
    qualification: 'ITC/Diploma in Civil Draftsman',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-24T10:00:00Z'
  },
  {
    id: '6',
    title: 'Ayurveda Therapist (Germany & Europe)',
    category: 'Abroad',
    description: 'Certified Ayurveda Therapist required for a leading wellness center in Europe. Must have knowledge of Panchakarma treatments and traditional massage techniques.',
    location: 'Germany / Europe Deployment',
    type: 'Full-time',
    salary_range: '₹1,50,000 - ₹2,50,000/month',
    qualification: 'BAMS / Diploma in Ayurveda Therapy',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-25T10:00:00Z'
  },
  {
    id: '7',
    title: 'Banking Operations Executive',
    category: 'Non-IT',
    description: 'Banking professional needed for customer service operations. Experience in retail banking, KYC verification, and loan processing preferred.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹22,000 - ₹35,000/month',
    qualification: 'Graduation / MBA Finance',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-26T10:00:00Z'
  },
  {
    id: '8',
    title: 'Senior Beautician',
    category: 'Non-IT',
    description: 'Experienced beautician with expertise in skincare, hair styling, and bridal makeup. CIDESCO or VLCC certification preferred.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹30,000/month',
    qualification: 'Certification in Cosmetology',
    experience: '3+ years',
    is_active: true,
    created_at: '2026-06-27T10:00:00Z'
  },
  {
    id: '9',
    title: 'BPO Voice Process Executive',
    category: 'Non-IT',
    description: 'Customer support executive for international voice process. Excellent English communication skills required. Rotational shifts.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹28,000/month',
    qualification: 'Higher Secondary / Any Degree',
    experience: 'Freshers & Experienced',
    is_active: true,
    created_at: '2026-06-28T10:00:00Z'
  },
  {
    id: '10',
    title: 'Business Development Manager',
    category: 'Non-IT',
    description: 'Dynamic BD Manager needed to identify new business opportunities, build client relationships, and drive revenue growth. MBA preferred.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹30,000 - ₹50,000/month',
    qualification: 'MBA Marketing / BBA',
    experience: '3+ years',
    is_active: true,
    created_at: '2026-06-28T11:00:00Z'
  },
  {
    id: '11',
    title: 'Retail Cashier',
    category: 'Non-IT',
    description: 'Cashier needed for a leading retail store. Must be comfortable with POS systems, cash handling, and customer interaction.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹12,000 - ₹18,000/month',
    qualification: '+2 / B.Com',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-28T12:00:00Z'
  },
  {
    id: '12',
    title: 'Computer Operator',
    category: 'IT',
    description: 'Computer operator with good typing speed and knowledge of MS Office required. Data entry and document management tasks.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹12,000 - ₹20,000/month',
    qualification: 'DCA / Any Degree',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-28T13:00:00Z'
  },
  {
    id: '13',
    title: 'Content Writer - Digital Media',
    category: 'Non-IT',
    description: 'Creative content writer for blog posts, social media content, and website copy. Strong command over English and SEO knowledge required.',
    location: 'Remote / Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹30,000/month',
    qualification: 'Degree in English/Journalism',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-28T14:00:00Z'
  },
  {
    id: '14',
    title: 'Head Chef - Multi-Cuisine (Dubai, UAE)',
    category: 'Abroad',
    description: 'Experienced head chef specializing in multi-cuisine cooking for a luxury hotel in Dubai. Must have hotel management background and 5+ years kitchen experience.',
    location: 'Dubai, UAE Deployment',
    type: 'Full-time',
    salary_range: '₹1,20,000 - ₹1,80,000/month',
    qualification: 'Degree/Diploma in Hotel Management',
    experience: '5+ years',
    is_active: true,
    created_at: '2026-06-28T15:00:00Z'
  },
  {
    id: '15',
    title: 'CRM Executive',
    category: 'Non-IT',
    description: 'CRM executive to manage customer relationships using Salesforce/HubSpot. Experience in customer engagement and retention strategies required.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹22,000 - ₹35,000/month',
    qualification: 'BBA / MBA',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-28T16:00:00Z'
  },
  {
    id: '16',
    title: 'Customer Relations Officer',
    category: 'Non-IT',
    description: 'Front-desk customer relations officer for a hospitality firm. Excellent communication and problem-solving skills essential.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹25,000/month',
    qualification: 'Any Degree',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-28T17:00:00Z'
  },
  {
    id: '17',
    title: 'Data Analyst',
    category: 'IT',
    description: 'Data analyst with expertise in Python, SQL, and Tableau. Will be responsible for data visualization, reporting, and actionable insights.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹30,000 - ₹50,000/month',
    qualification: 'B.Tech / BCA / MCA',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-28T18:00:00Z'
  },
  {
    id: '18',
    title: 'Data Entry Operator',
    category: 'Non-IT',
    description: 'Data entry operator with minimum 35 WPM typing speed. Accuracy and attention to detail are critical. MS Excel proficiency required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹12,000 - ₹18,000/month',
    qualification: '+2 / Graduation',
    experience: 'Freshers & Experienced',
    is_active: true,
    created_at: '2026-06-28T19:00:00Z'
  },
  {
    id: '19',
    title: 'Digital Marketing Executive',
    category: 'IT',
    description: 'Digital marketing professional for SEO, SEM, social media marketing, and email campaigns. Google Ads certification is a plus.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹35,000/month',
    qualification: 'Certification in Digital Marketing',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-28T20:00:00Z'
  },
  {
    id: '20',
    title: 'Company Driver',
    category: 'Non-IT',
    description: 'Licensed driver with clean record needed for corporate transportation. Must have valid LMV license and knowledge of city routes.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹22,000/month',
    qualification: 'SSLC / Valid LMV License',
    experience: '3+ years',
    is_active: true,
    created_at: '2026-06-28T21:00:00Z'
  },
  {
    id: '21',
    title: 'Licensed Electrician',
    category: 'Non-IT',
    description: 'Certified electrician for commercial and residential wiring, maintenance, and troubleshooting. Wireman license required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹30,000/month',
    qualification: 'ITI Electrical / Wireman License',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-28T22:00:00Z'
  },
  {
    id: '22',
    title: 'Civil Engineer - Site (Saudi Arabia)',
    category: 'Abroad',
    description: 'Site civil engineer for construction projects in Riyadh. B.Tech in Civil Engineering required. Experience in estimation and project management preferred.',
    location: 'Riyadh, Saudi Arabia Deployment',
    type: 'Full-time',
    salary_range: '₹1,50,000 - ₹2,20,000/month',
    qualification: 'B.Tech Civil Engineering',
    experience: '3+ years',
    is_active: true,
    created_at: '2026-06-28T23:00:00Z'
  },
  {
    id: '23',
    title: 'Mechanical Engineer (Qatar)',
    category: 'Abroad',
    description: 'Mechanical engineer for oil & gas refinery site. Must have experience in AutoCAD, SolidWorks, and production planning.',
    location: 'Doha, Qatar Deployment',
    type: 'Full-time',
    salary_range: '₹1,80,000 - ₹2,50,000/month',
    qualification: 'B.Tech Mechanical Engineering',
    experience: '4+ years',
    is_active: true,
    created_at: '2026-06-28T23:30:00Z'
  },
  {
    id: '24',
    title: 'Sales Executive',
    category: 'Non-IT',
    description: 'Sales executive for FMCG products. Must have own vehicle, good communication skills, and willingness to travel within Kerala.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹28,000/month',
    qualification: '+2 / Graduation',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-28T23:45:00Z'
  },
  {
    id: '25',
    title: 'Faculty - Computer Science',
    category: 'Non-IT',
    description: 'Computer Science faculty for engineering college. M.Tech/PhD required. Teaching experience in programming, DBMS, and networking preferred.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹30,000 - ₹50,000/month',
    qualification: 'M.Tech / PhD in Computer Science',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-28T23:50:00Z'
  },
  {
    id: '26',
    title: 'Fashion Designer',
    category: 'Non-IT',
    description: 'Creative fashion designer for a boutique brand. Must have portfolio showcasing original designs. Knowledge of textile science preferred.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹35,000/month',
    qualification: 'Degree in Fashion Designing',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-28T23:55:00Z'
  },
  {
    id: '27',
    title: 'Finance Manager',
    category: 'Non-IT',
    description: 'Finance manager with CA/MBA Finance for financial planning, budgeting, and compliance. Experience in SAP/ERP systems preferred.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹40,000 - ₹70,000/month',
    qualification: 'CA / MBA Finance',
    experience: '5+ years',
    is_active: true,
    created_at: '2026-06-28T23:57:00Z'
  },
  {
    id: '28',
    title: 'Graphic Designer',
    category: 'IT',
    description: 'Creative graphic designer proficient in Adobe Creative Suite (Photoshop, Illustrator, InDesign). Portfolio required. Experience in branding preferred.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹18,000 - ₹30,000/month',
    qualification: 'Degree/Diploma in Graphic Design',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-28T23:58:00Z'
  },
  {
    id: '29',
    title: 'Production Helper',
    category: 'Non-IT',
    description: 'Helper needed for production unit. Physical fitness required. Will assist in loading, unloading, and assembly tasks.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹10,000 - ₹15,000/month',
    qualification: 'SSLC / 10th standard',
    experience: 'Freshers',
    is_active: true,
    created_at: '2026-06-28T23:59:00Z'
  },
  {
    id: '30',
    title: 'HR Consultant',
    category: 'Non-IT',
    description: 'Experienced HR consultant for recruitment, employee engagement, and compliance management. SHRM/HRCI certification is a plus.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹30,000 - ₹50,000/month',
    qualification: 'MBA HR / MSW',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-29T00:00:00Z'
  },
  {
    id: '31',
    title: 'Interior Designer',
    category: 'Non-IT',
    description: 'Creative interior designer for residential and commercial projects. Proficiency in SketchUp, 3Ds Max, and AutoCAD required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹25,000 - ₹40,000/month',
    qualification: 'B.Des / Diploma in Interior Design',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-29T01:00:00Z'
  },
  {
    id: '32',
    title: 'IT Support Engineer',
    category: 'IT',
    description: 'IT support engineer for hardware/software troubleshooting, network management, and system administration. CCNA certification preferred.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹35,000/month',
    qualification: 'B.Tech / B.Sc Computer Science / CCNA',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-29T02:00:00Z'
  },
  {
    id: '33',
    title: 'Java Developer',
    category: 'IT',
    description: 'Java developer with Spring Boot experience for enterprise application development. 2+ years experience in Java, REST APIs, and microservices.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹35,000 - ₹60,000/month',
    qualification: 'B.Tech / MCA / BCA',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-29T03:00:00Z'
  },
  {
    id: '34',
    title: 'Lab Technician - Pathology',
    category: 'Non-IT',
    description: 'Certified lab technician for diagnostic laboratory. DMLT/BMLT qualification required. Experience in sample collection and reporting.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹25,000/month',
    qualification: 'DMLT / BMLT',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-29T04:00:00Z'
  },
  {
    id: '35',
    title: 'Operations Manager',
    category: 'Non-IT',
    description: 'Operations manager to oversee daily business activities, manage teams, and optimize processes. MBA with 5+ years experience preferred.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹40,000 - ₹65,000/month',
    qualification: 'MBA Operations / B.Tech',
    experience: '5+ years',
    is_active: true,
    created_at: '2026-06-29T05:00:00Z'
  },
  {
    id: '36',
    title: 'Automobile Mechanic',
    category: 'Non-IT',
    description: 'Skilled automobile mechanic for a multi-brand service center. Must have ITI/Diploma in automobile engineering and hands-on experience.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹28,000/month',
    qualification: 'ITI / Diploma in Automobile Engineering',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-29T06:00:00Z'
  },
  {
    id: '37',
    title: 'Medical Representative',
    category: 'Non-IT',
    description: 'Medical representative for pharmaceutical company covering Thiruvananthapuram district. B.Pharm/B.Sc preferred. Own vehicle required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹20,000 - ₹35,000/month',
    qualification: 'B.Pharm / B.Sc',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-29T07:00:00Z'
  },
  {
    id: '38',
    title: 'Mobile App Developer - Flutter',
    category: 'IT',
    description: 'Flutter developer for cross-platform mobile app development. Experience with Dart, REST APIs, and state management (Bloc/Provider) required.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹30,000 - ₹55,000/month',
    qualification: 'B.Tech / MCA / BCA',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-29T08:00:00Z'
  },
  {
    id: '39',
    title: 'Network Administrator',
    category: 'IT',
    description: 'Network administrator for enterprise network infrastructure management. CCNA/CCNP certification and experience with Cisco equipment required.',
    location: 'Technopark, Thiruvananthapuram',
    type: 'Full-time',
    salary_range: '₹28,000 - ₹45,000/month',
    qualification: 'B.Tech / B.Sc / CCNA',
    experience: '2+ years',
    is_active: true,
    created_at: '2026-06-29T09:00:00Z'
  },
  {
    id: '40',
    title: 'Staff Nurse - ICU (United Kingdom)',
    category: 'Abroad',
    description: 'Registered nurse for ICU department in NHS Hospital UK. BSc Nursing with active registration required. IELTS/OET credentials necessary.',
    location: 'United Kingdom Deployment',
    type: 'Full-time',
    salary_range: '₹2,50,000 - ₹3,50,000/month',
    qualification: 'B.Sc Nursing / GNM + KNMC + OET/IELTS',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-29T10:00:00Z'
  },
  {
    id: '41',
    title: 'Office Coordinator',
    category: 'Non-IT',
    description: 'Office coordinator to manage schedules, coordinate meetings, and handle correspondence. Strong MS Office skills and organizational abilities required.',
    location: 'Thiruvananthapuram, Kerala',
    type: 'Full-time',
    salary_range: '₹15,000 - ₹25,000/month',
    qualification: 'Graduation / PG',
    experience: '1+ years',
    is_active: true,
    created_at: '2026-06-29T11:00:00Z'
  }
];
